-- ═══════════════════════════════════════════════════════════════════════
--  Semantic Search Infrastructure
--  Adds pgvector extension and a dedicated embeddings table within the
--  search schema for semantic / hybrid search support.
-- ═══════════════════════════════════════════════════════════════════════

-- Enable the pgvector extension (idempotent)
CREATE EXTENSION IF NOT EXISTS vector;

-- Ensure the search schema exists
CREATE SCHEMA IF NOT EXISTS search;

-- ── Embeddings Table ────────────────────────────────────────────────
-- Stores entity embeddings generated by the embedding service. Each
-- row represents a single entity's vector representation along with
-- metadata for filtering and provenance tracking.
CREATE TABLE IF NOT EXISTS search.embeddings (
  id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  entity_type   text        NOT NULL,
  entity_id     uuid        NOT NULL,
  entity_name   text        NOT NULL,
  embedding     vector(1536),
  metadata      jsonb       DEFAULT '{}',
  created_at    timestamptz DEFAULT now(),
  updated_at    timestamptz DEFAULT now()
);

-- ── Indexes ─────────────────────────────────────────────────────────

-- HNSW index for fast approximate nearest-neighbour cosine similarity
-- searches. HNSW provides better recall than IVFFlat for most workloads.
CREATE INDEX IF NOT EXISTS idx_embeddings_vector
  ON search.embeddings
  USING hnsw (embedding vector_cosine_ops);

-- B-tree index for filtering by entity type + id (used in upsert and
-- targeted lookups).
CREATE INDEX IF NOT EXISTS idx_embeddings_entity
  ON search.embeddings (entity_type, entity_id);
